import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useGeneStore } from "../store";
export function SequencePanel() {
    const { sequenceAnalysis } = useGeneStore();
    if (!sequenceAnalysis)
        return null;
    const { primary_orf, cai, gc_profile, cpg_islands, splice_sites, seq_length, codon_usage } = sequenceAnalysis;
    // Top 10 most-used codons
    const topCodons = [...codon_usage].sort((a, b) => b.count - a.count).slice(0, 10);
    return (_jsxs("div", { className: "panel sequence-panel", children: [_jsx("h2", { className: "panel-title", children: "Sequence Analysis" }), _jsxs("div", { className: "stats-grid", children: [_jsx(StatCard, { label: "Length", value: `${seq_length.toLocaleString()} bp` }), _jsx(StatCard, { label: "GC Content", value: `${gc_profile.overall}%` }), _jsx(StatCard, { label: "CAI", value: cai.toFixed(3), sub: "Codon Adaptation Index" }), _jsx(StatCard, { label: "CpG Islands", value: String(cpg_islands.length) }), _jsx(StatCard, { label: "Splice Sites", value: String(splice_sites.length), sub: "high-confidence" })] }), primary_orf && (_jsxs("div", { className: "subsection", children: [_jsx("h3", { children: "Primary ORF" }), _jsxs("p", { children: ["Position ", primary_orf.start, "\u2013", primary_orf.end, " (frame ", primary_orf.frame, "),", " ", _jsxs("strong", { children: [primary_orf.length_aa, " amino acids"] })] })] })), gc_profile.profile.length > 0 && (_jsxs("div", { className: "subsection", children: [_jsx("h3", { children: "GC Content Profile" }), _jsx("div", { className: "gc-sparkline", children: gc_profile.profile.map((gc, i) => (_jsx("div", { className: "gc-bar", style: {
                                height: `${gc}%`,
                                backgroundColor: gc > 60 ? "#e74c3c" : gc > 40 ? "#3498db" : "#95a5a6",
                            }, title: `Window ${i}: ${gc}% GC` }, i))) }), _jsxs("p", { className: "gc-legend", children: [gc_profile.profile.length, " windows of ", gc_profile.window_size, " bp"] })] })), cpg_islands.length > 0 && (_jsxs("div", { className: "subsection", children: [_jsx("h3", { children: "CpG Islands" }), _jsxs("table", { className: "data-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Start" }), _jsx("th", { children: "End" }), _jsx("th", { children: "Length" }), _jsx("th", { children: "GC%" }), _jsx("th", { children: "Obs/Exp" })] }) }), _jsx("tbody", { children: cpg_islands.map((island, i) => (_jsxs("tr", { children: [_jsx("td", { children: island.start.toLocaleString() }), _jsx("td", { children: island.end.toLocaleString() }), _jsx("td", { children: island.length }), _jsxs("td", { children: [island.gc_percent, "%"] }), _jsx("td", { children: island.obs_exp_ratio })] }, i))) })] })] })), topCodons.length > 0 && (_jsxs("div", { className: "subsection", children: [_jsx("h3", { children: "Top Codons" }), _jsx("div", { className: "codon-grid", children: topCodons.map((c) => (_jsxs("div", { className: "codon-item", children: [_jsx("code", { children: c.codon }), _jsx("span", { className: "codon-aa", children: c.amino_acid }), _jsxs("span", { className: "codon-count", children: [c.count, "x"] }), _jsxs("span", { className: "codon-rscu", children: ["RSCU ", c.rscu] })] }, c.codon))) })] }))] }));
}
function StatCard({ label, value, sub }) {
    return (_jsxs("div", { className: "stat-card", children: [_jsx("div", { className: "stat-value", children: value }), _jsx("div", { className: "stat-label", children: label }), sub && _jsx("div", { className: "stat-sub", children: sub })] }));
}
