"""add_gene_graduation_fields

Revision ID: f8c66d251166
Revises: b078386f2db8
Create Date: 2026-02-07 23:01:18.820779
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c66d251166'
down_revision: Union[str, None] = 'b078386f2db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genes', sa.Column('proposed_function', sa.String(length=500), nullable=True))
    op.add_column('genes', sa.Column('graduated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('genes', sa.Column('graduation_hypothesis_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_genes_graduated_at'), 'genes', ['graduated_at'], unique=False)
    op.create_foreign_key(op.f('fk_genes_graduation_hypothesis_id_hypotheses'), 'genes', 'hypotheses', ['graduation_hypothesis_id'], ['hypothesis_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_genes_graduation_hypothesis_id_hypotheses'), 'genes', type_='foreignkey')
    op.drop_index(op.f('ix_genes_graduated_at'), table_name='genes')
    op.drop_column('genes', 'graduation_hypothesis_id')
    op.drop_column('genes', 'graduated_at')
    op.drop_column('genes', 'proposed_function')
    # ### end Alembic commands ###
